apiVersion: v1
kind: Namespace
metadata:
  name: vlans

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vlan-provisioning
  namespace: vlans

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: vlan-provisioning-role
  namespace: vlans
rules:
- apiGroups: ["example.com"]
  resources: ["vlans"]
  verbs: ["get", "list", "watch", "update"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vlan-provisioning-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: vlan-provisioning
    namespace: vlans

